# Array Manipulations


In [2]:
import numpy as np

In [4]:
x = np.arange(6)

print(x)

[0 1 2 3 4 5]


In [6]:
y = x.reshape((2,3))
print(y)

[[0 1 2]
 [3 4 5]]


In [10]:
x = np.array([[0,1,2],[3,4,5]], dtype= np.uint8)

print(x)

[[0 1 2]
 [3 4 5]]


In [11]:
y = np.reshape(x,6)

print(y)

[0 1 2 3 4 5]


In [13]:
y = np.ravel(x)
y

array([0, 1, 2, 3, 4, 5], dtype=uint8)

In [16]:
y = x.flatten()

print(y)

[0 1 2 3 4 5]


In [17]:
y = x.flatten('C')

print(y)

[0 1 2 3 4 5]


In [18]:
y = x.flatten('F')

print(y)

[0 3 1 4 2 5]


### Join multiple Arrays

In [23]:
x = np.array([1,2,3], dtype= np.uint8)
y = np.array([4,5,6],dtype= np.uint8)

print(x.dtype)

print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [25]:
z= np.stack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [26]:
z= np.stack((x,y), axis= 0)
print(z)

[[1 2 3]
 [4 5 6]]


In [27]:
z= np.stack((x,y), axis= -1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
print(x)
print(y)

[1 2 3]
[4 5 6]


In [30]:
z= np.dstack((x,y))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [31]:
print(z.shape)

(1, 3, 2)


In [32]:
#horizontal Stack
z= np.hstack((x,y))
print(z)

[1 2 3 4 5 6]


In [33]:
#Vertical Stack
z= np.vstack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [34]:
z.shape

(2, 3)

In [35]:
x = np.arange(9)

print(x)

[0 1 2 3 4 5 6 7 8]


In [37]:
a,b,c = np.split(x,3)

print(a,b,c)

[0 1 2] [3 4 5] [6 7 8]


In [42]:
x = np.random.rand(4,4,4)

print(x)

[[[0.48628834 0.38159125 0.41147731 0.7889973 ]
  [0.58060307 0.90633044 0.06564746 0.13131704]
  [0.08162168 0.63011559 0.21658706 0.63759212]
  [0.72635067 0.46612148 0.717482   0.10866135]]

 [[0.95914689 0.87661038 0.90885474 0.86112315]
  [0.80507987 0.3395552  0.97881883 0.39297374]
  [0.74593277 0.52416369 0.43137201 0.10819255]
  [0.47606649 0.25061941 0.4646     0.64190086]]

 [[0.44086723 0.4608477  0.13951619 0.901479  ]
  [0.95918629 0.25816426 0.75777344 0.49037544]
  [0.04364212 0.41433544 0.62289356 0.2310975 ]
  [0.5900699  0.22948667 0.9036638  0.2781361 ]]

 [[0.57746469 0.55338144 0.12661939 0.75499267]
  [0.11087236 0.70688794 0.18812292 0.30067635]
  [0.57754816 0.63458033 0.59093843 0.94911369]
  [0.41468257 0.03230464 0.05278948 0.38968047]]]


In [46]:
#Split it in 2 matrices
y,z = np.split(x, 2)
print(y,z)

[[[0.48628834 0.38159125 0.41147731 0.7889973 ]
  [0.58060307 0.90633044 0.06564746 0.13131704]
  [0.08162168 0.63011559 0.21658706 0.63759212]
  [0.72635067 0.46612148 0.717482   0.10866135]]

 [[0.95914689 0.87661038 0.90885474 0.86112315]
  [0.80507987 0.3395552  0.97881883 0.39297374]
  [0.74593277 0.52416369 0.43137201 0.10819255]
  [0.47606649 0.25061941 0.4646     0.64190086]]] [[[0.44086723 0.4608477  0.13951619 0.901479  ]
  [0.95918629 0.25816426 0.75777344 0.49037544]
  [0.04364212 0.41433544 0.62289356 0.2310975 ]
  [0.5900699  0.22948667 0.9036638  0.2781361 ]]

 [[0.57746469 0.55338144 0.12661939 0.75499267]
  [0.11087236 0.70688794 0.18812292 0.30067635]
  [0.57754816 0.63458033 0.59093843 0.94911369]
  [0.41468257 0.03230464 0.05278948 0.38968047]]]


In [47]:
y,z = np.dsplit(x, 2)
print(y,z)

[[[0.48628834 0.38159125]
  [0.58060307 0.90633044]
  [0.08162168 0.63011559]
  [0.72635067 0.46612148]]

 [[0.95914689 0.87661038]
  [0.80507987 0.3395552 ]
  [0.74593277 0.52416369]
  [0.47606649 0.25061941]]

 [[0.44086723 0.4608477 ]
  [0.95918629 0.25816426]
  [0.04364212 0.41433544]
  [0.5900699  0.22948667]]

 [[0.57746469 0.55338144]
  [0.11087236 0.70688794]
  [0.57754816 0.63458033]
  [0.41468257 0.03230464]]] [[[0.41147731 0.7889973 ]
  [0.06564746 0.13131704]
  [0.21658706 0.63759212]
  [0.717482   0.10866135]]

 [[0.90885474 0.86112315]
  [0.97881883 0.39297374]
  [0.43137201 0.10819255]
  [0.4646     0.64190086]]

 [[0.13951619 0.901479  ]
  [0.75777344 0.49037544]
  [0.62289356 0.2310975 ]
  [0.9036638  0.2781361 ]]

 [[0.12661939 0.75499267]
  [0.18812292 0.30067635]
  [0.59093843 0.94911369]
  [0.05278948 0.38968047]]]


In [48]:
y,z = np.hsplit(x, 2)
print(y,z)

[[[0.48628834 0.38159125 0.41147731 0.7889973 ]
  [0.58060307 0.90633044 0.06564746 0.13131704]]

 [[0.95914689 0.87661038 0.90885474 0.86112315]
  [0.80507987 0.3395552  0.97881883 0.39297374]]

 [[0.44086723 0.4608477  0.13951619 0.901479  ]
  [0.95918629 0.25816426 0.75777344 0.49037544]]

 [[0.57746469 0.55338144 0.12661939 0.75499267]
  [0.11087236 0.70688794 0.18812292 0.30067635]]] [[[0.08162168 0.63011559 0.21658706 0.63759212]
  [0.72635067 0.46612148 0.717482   0.10866135]]

 [[0.74593277 0.52416369 0.43137201 0.10819255]
  [0.47606649 0.25061941 0.4646     0.64190086]]

 [[0.04364212 0.41433544 0.62289356 0.2310975 ]
  [0.5900699  0.22948667 0.9036638  0.2781361 ]]

 [[0.57754816 0.63458033 0.59093843 0.94911369]
  [0.41468257 0.03230464 0.05278948 0.38968047]]]


In [49]:
y,z = np.vsplit(x, 2)
print(y,z)

[[[0.48628834 0.38159125 0.41147731 0.7889973 ]
  [0.58060307 0.90633044 0.06564746 0.13131704]
  [0.08162168 0.63011559 0.21658706 0.63759212]
  [0.72635067 0.46612148 0.717482   0.10866135]]

 [[0.95914689 0.87661038 0.90885474 0.86112315]
  [0.80507987 0.3395552  0.97881883 0.39297374]
  [0.74593277 0.52416369 0.43137201 0.10819255]
  [0.47606649 0.25061941 0.4646     0.64190086]]] [[[0.44086723 0.4608477  0.13951619 0.901479  ]
  [0.95918629 0.25816426 0.75777344 0.49037544]
  [0.04364212 0.41433544 0.62289356 0.2310975 ]
  [0.5900699  0.22948667 0.9036638  0.2781361 ]]

 [[0.57746469 0.55338144 0.12661939 0.75499267]
  [0.11087236 0.70688794 0.18812292 0.30067635]
  [0.57754816 0.63458033 0.59093843 0.94911369]
  [0.41468257 0.03230464 0.05278948 0.38968047]]]


In [51]:
x =np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
y= np.flip(x, axis= -1)
y

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [54]:
y= np.flip(x, axis= 0)
y

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [55]:
#fliping left to right

y= np.fliplr(x)
y

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [58]:
#flip up down
y= np.flipud(x)
y

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [60]:
y = np.roll(x,8)

y

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [63]:
y = np.rot90(x)

y, x

(array([[ 3,  7, 11, 15],
        [ 2,  6, 10, 14],
        [ 1,  5,  9, 13],
        [ 0,  4,  8, 12]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))