In [1]:
#Dot Product
import numpy as np 


In [3]:
print(np.dot(10,5))

50


In [5]:
a = np.array ([2,4], np.uint8)
b = np.array ([5,6], np.uint8)

print(np.dot(a,b))

34


In [11]:
a = np.array ([[2,4], [5,8]], np.uint8)
b = np.array ([[5,6], [9,3]], np.uint8)

print(np.dot(a,b))

[[46 24]
 [97 54]]


In [17]:
a = np.random.rand(10,5)
b = np.random.rand(5,2)
c = np.random.rand(2,3)
d = np.random.rand(3,4)


In [19]:
e = np.linalg.multi_dot([a, b ,c, d])
print(e)

[[1.90111234 1.18798    1.6524892  3.87646503]
 [1.24634481 0.79079683 1.07935935 2.53218615]
 [1.43008402 0.90377662 1.23968178 2.90824702]
 [1.4845691  0.95730549 1.28054662 3.00441589]
 [1.57553676 0.99520501 1.36593355 3.20442115]
 [2.22188232 1.4161633  1.92206227 4.50927541]
 [2.35208581 1.509973   2.03108841 4.76522861]
 [1.48729811 0.94190129 1.28862265 3.02309153]
 [2.70499609 1.7293135  2.3382421  5.48574139]
 [1.68891675 1.05828752 1.46707535 3.44156071]]


# Vector Dot Product

In [20]:
a = np.array([1,2])
b = np.array([3,4])

print(np.vdot(a,b))

11


In [ ]:
a = np.array([1+5j,2 + 3j])
b = np.array([3+2j , 4+ 7j])

print(np.vdot(a,b))

## Inner Product

In [22]:
a = np.array([1,2,3,4,5,6])
b = np.array([0,1,0,1,0,1])

print(np.inner(a,b))

12


In [23]:

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[0,1,0],[1,0,1]])

print(np.inner(a,b))

[[ 2  4]
 [ 5 10]]


# QR Decomposition

In [24]:
a = np.random. rand(3,3)

print(a)

[[0.59859588 0.82927851 0.65353509]
 [0.00401448 0.5126824  0.87283359]
 [0.12826879 0.98917652 0.70168159]]


In [25]:
q, r = np.linalg.qr(a)
print('q=',q,'\n\nr = ' , r , '\n')

print(np.dot(q,r))

q= [[-0.97778198  0.18010957 -0.1072518 ]
 [-0.00655749 -0.53766792 -0.84313119]
 [-0.20952185 -0.82369518  0.52690307]] 

r =  [[-0.6121977  -1.02146959 -0.79175606]
 [ 0.         -0.94107181 -0.92955844]
 [ 0.          0.         -0.43628787]] 

[[0.59859588 0.82927851 0.65353509]
 [0.00401448 0.5126824  0.87283359]
 [0.12826879 0.98917652 0.70168159]]


# Determinant and Solving Linear Equations

In [29]:
a = np.array([[5, 6],[3, 4]])

print(np.linalg.det(a))

2.0000000000000004


In [33]:
a = np.array([[2,1, -3],[4,-2, 1],[3,5, -2]], np.int16)
b = np.array([-4,9, 5], np.int16)

x = np.linalg.solve(a,b)
print(x)

[2. 1. 3.]
