In [1]:
import numpy as np

In [4]:
x= np.random.randint (low = 0 , high= 9, size=10)
print(x)

[3 0 7 8 6 8 7 0 5 5]


In [6]:
x = np.random.rand(3,3)

print(x)

[[0.57523055 0.62267518 0.53599597]
 [0.23402188 0.38446443 0.99992362]
 [0.85140662 0.50307681 0.0401862 ]]
