In [2]:
import numpy as np

import scipy.linalg
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print('\n' , scipy.linalg.inv(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [9]:
# ax = b
a = np.array([[2,1, -3], [4,-2,1], [3,5,-2]])

b = np. array([-4,9,5])

print(scipy.linalg.solve(a,b))

[2. 1. 3.]


In [13]:


a = np.array([[0,2,3],[4,5,6],[7,8,9]])


print(scipy.linalg.det(a))

3.000000000000001


In [14]:


print(scipy.linalg.norm(a))

16.852299546352718


In [15]:
a = np.arange(36).reshape((6,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [17]:


print(scipy.linalg.tril(a, k=0))

[[ 0  0  0  0  0  0]
 [ 6  7  0  0  0  0]
 [12 13 14  0  0  0]
 [18 19 20 21  0  0]
 [24 25 26 27 28  0]
 [30 31 32 33 34 35]]


In [18]:
print(scipy.linalg.tril(a, k=1))

[[ 0  1  0  0  0  0]
 [ 6  7  8  0  0  0]
 [12 13 14 15  0  0]
 [18 19 20 21 22  0]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [19]:
print(scipy.linalg.tril(a, k=-1))

[[ 0  0  0  0  0  0]
 [ 6  0  0  0  0  0]
 [12 13  0  0  0  0]
 [18 19 20  0  0  0]
 [24 25 26 27  0  0]
 [30 31 32 33 34  0]]


In [20]:
print(scipy.linalg.triu(a, k=0))

[[ 0  1  2  3  4  5]
 [ 0  7  8  9 10 11]
 [ 0  0 14 15 16 17]
 [ 0  0  0 21 22 23]
 [ 0  0  0  0 28 29]
 [ 0  0  0  0  0 35]]


In [23]:
print(scipy.linalg.triu(a, k=1))

[[ 0  1  2  3  4  5]
 [ 0  0  8  9 10 11]
 [ 0  0  0 15 16 17]
 [ 0  0  0  0 22 23]
 [ 0  0  0  0  0 29]
 [ 0  0  0  0  0  0]]


In [24]:
print(scipy.linalg.triu(a, k=-1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [ 0 13 14 15 16 17]
 [ 0  0 20 21 22 23]
 [ 0  0  0 27 28 29]
 [ 0  0  0  0 34 35]]


In [25]:
a = np.arange(49).reshape((7,7))
print(a)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


In [27]:
p,l,u = scipy.linalg.lu(a)
#Per mutation matrix

print(p)

print(l)

print(u)


[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 8.33333333e-01  1.66666667e-01  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.66666667e-01  8.33333333e-01  1.42857143e-01  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.66666667e-01  3.33333333e-01  5.00000000e-01  5.00000000e-01
   1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.33333333e-01  6.66666667e-01  2.14285714e-01 -3.33066907e-16
   1.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 5.00000000e-01  5.00000000e-01 -0.00000000e+00  0.00000000e+00
  -0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 4.200000

In [29]:
a  = np .arange(9).reshape((3,3))
q,r = scipy.linalg.qr(a)

print(q)

print(r)

[[ 0.          0.91287093  0.40824829]
 [-0.4472136   0.36514837 -0.81649658]
 [-0.89442719 -0.18257419  0.40824829]]
[[-6.70820393e+00 -8.04984472e+00 -9.39148551e+00]
 [ 0.00000000e+00  1.09544512e+00  2.19089023e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.65307819e-16]]


In [30]:

q,r = scipy.linalg.rq(a)

print(q)

print(r)

[[-1.21153320e-16  1.20402011e+00 -1.88423342e+00]
 [ 0.00000000e+00  6.02010056e-01 -7.04539452e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.22065556e+01]]
[[ 0.40824829 -0.81649658  0.40824829]
 [-0.76923507 -0.06689001  0.63545506]
 [-0.49153915 -0.57346234 -0.65538554]]
