In [1]:
import numpy as np

In [7]:
a= np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [8]:
#Matrix Multiply

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [10]:
#find determinant

c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [11]:
stats= np.array([[1,2,3],[4,5,6]])

In [12]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.min(stats)

1

In [14]:
np.max(stats)

6

In [15]:
np.sum(stats)

21

## Reorganizing Arrays

In [20]:
before= np.array([[1,2,3,4],[5,6,7,8]])

In [21]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [24]:
#Vertical Stacking Vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])
#or keep passing 
np.vstack([v1,v2,v1,v1,v1])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [27]:
#Horizotal Stacking Vectors

h1 = np.ones((2,4))

h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])