### Mathematics

In [2]:
import numpy as np

In [3]:
a= np. array([2,3,6,3,7,4,3,5])

In [4]:
a+2

array([4, 5, 8, 5, 9, 6, 5, 7])

In [5]:
a-5

array([-3, -2,  1, -2,  2, -1, -2,  0])

In [6]:
a*2

array([ 4,  6, 12,  6, 14,  8,  6, 10])

In [7]:
a/1

array([2., 3., 6., 3., 7., 4., 3., 5.])

In [8]:
np.sin(a)

array([ 0.90929743,  0.14112001, -0.2794155 ,  0.14112001,  0.6569866 ,
       -0.7568025 ,  0.14112001, -0.95892427])

In [9]:
np.cos(a)

array([-0.41614684, -0.9899925 ,  0.96017029, -0.9899925 ,  0.75390225,
       -0.65364362, -0.9899925 ,  0.28366219])

In [10]:
np.tan(a)

array([-2.18503986, -0.14254654, -0.29100619, -0.14254654,  0.87144798,
        1.15782128, -0.14254654, -3.38051501])

# Linear Algebra


In [14]:
a = np.ones((2,3))
print(a)

b= np.full((3,2),4)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]
